# Generated by Django 4.2.6 on 2024-01-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_metadata', models.TextField(null=True)),
                ('session_key', models.CharField(max_length=255, null=True)),
                ('user_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JsonWebToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('inactive_time', models.DateTimeField(null=True)),
                ('token', models.TextField()),
                ('request_metadata', models.TextField(null=True)),
                ('session_key', models.CharField(max_length=255, null=True)),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoginCaptcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('captcha_id', models.CharField(max_length=255, unique=True)),
                ('captcha_value', models.CharField(max_length=25)),
                ('active', models.BooleanField(default=True)),
                ('image_generated', models.BooleanField(default=False)),
                ('session_key', models.CharField(max_length=255, null=True)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
