# Generated by Django 4.2.6 on 2024-01-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_graphbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logincaptcha',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
