# Generated by Django 2.2.1 on 2023-02-23 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('rol', models.CharField(choices=[('SOPORTE', 'SOPORTE'), ('RESPONSABLE', 'RESPONSABLE'), ('AUXILIAR', 'AUXILIAR')], max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('social_id', models.CharField(blank=True, max_length=100, null=True)),
                ('social_origin', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_integer_field', models.BigIntegerField()),
                ('boolean_field', models.BooleanField()),
                ('char_field', models.CharField(max_length=100)),
                ('date_field', models.DateField()),
                ('date_time_field', models.DateTimeField()),
                ('decimal_field', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_field', models.DurationField()),
                ('email_field', models.EmailField(max_length=254)),
                ('file_field', models.FileField(upload_to='')),
                ('file_path_field', models.FilePathField()),
                ('float_field', models.FloatField()),
                ('image_field', models.ImageField(upload_to='')),
                ('integer_field', models.IntegerField()),
                ('generic_ip_address_field', models.GenericIPAddressField()),
                ('positive_integer_field', models.PositiveIntegerField()),
                ('positive_small_integer_field', models.PositiveSmallIntegerField()),
                ('slug_field', models.SlugField()),
                ('small_integer_field', models.SmallIntegerField()),
                ('text_field', models.TextField()),
                ('time_field', models.TimeField()),
                ('url_field', models.URLField()),
                ('uuid_field', models.UUIDField()),
                ('foreign_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='prueba.RelatedModel')),
            ],
        ),
    ]
