# Generated by Django 2.2.1 on 2023-02-24 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('rol', models.CharField(choices=[('SOPORTE', 'SOPORTE'), ('RESPONSABLE', 'RESPONSABLE'), ('AUXILIAR', 'AUXILIAR')], max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos')),
                ('social_id', models.CharField(blank=True, max_length=100, null=True)),
                ('social_origin', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_integer_field', models.BigIntegerField(blank=True, null=True)),
                ('boolean_field', models.BooleanField(blank=True, null=True)),
                ('char_field', models.CharField(max_length=100)),
                ('date_field', models.DateField(blank=True, null=True)),
                ('date_time_field', models.DateTimeField(blank=True, null=True)),
                ('decimal_field', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_field', models.DurationField(blank=True, null=True)),
                ('email_field', models.EmailField(blank=True, max_length=254, null=True)),
                ('file_field', models.FileField(blank=True, null=True, upload_to='')),
                ('file_path_field', models.FilePathField(blank=True, null=True)),
                ('float_field', models.FloatField(blank=True, null=True)),
                ('image_field', models.ImageField(blank=True, null=True, upload_to='')),
                ('integer_field', models.IntegerField(blank=True, null=True)),
                ('generic_ip_address_field', models.GenericIPAddressField(blank=True, null=True)),
                ('positive_integer_field', models.PositiveIntegerField(blank=True, null=True)),
                ('positive_small_integer_field', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('slug_field', models.SlugField(blank=True, null=True)),
                ('small_integer_field', models.SmallIntegerField(blank=True, null=True)),
                ('text_field', models.TextField(blank=True, null=True)),
                ('time_field', models.TimeField(blank=True, null=True)),
                ('url_field', models.URLField(blank=True, null=True)),
                ('uuid_field', models.UUIDField(blank=True, null=True)),
                ('foreign_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas', to='prueba.RelatedModel')),
            ],
        ),
    ]
